### PR TITLE
Fix first time setup script

### LINKED ISSUE #29: No such file or directory error in version 0.15.3
Hello,

Running the 0.15.3 version gives me the following error:
```
core@core-01 ~ $ docker logs bookstack
/docker-entrypoint.sh: line 12: /var/www/BookStack/.env: No such file or directory
```

0.14.3 does not give this message

### PR DESCRIPTION
**Pull request by hgmich**
The script wasn’t switched from `/var/www/BookStack` to `/var/www/bookstack`. 
Resolves #29.

### CODE REVIEW

**Comment by solidnerd** [comment]
Thanks. Yeah I missed that. I would prefer a better solution we cloud use $BOOKSTACK_HOME instead of the path so we don't need to worry anymore in the future.

File: docker-entrypoint.sh [hunk 1]
```diff
@@ -7,9 +7,9 @@ echoerr() { echo "$@" 1>&2; }
 IFS=":" read -r DB_HOST_NAME DB_PORT <<< "$DB_HOST"
 DB_PORT=${DB_PORT:-3306}
 
-if [ ! -f '/var/www/BookStack/.env' ]; then
+if [ ! -f '/var/www/bookstack/.env' ]; then
```
Comment (solidnerd) [inline docker-entrypoint.sh]: Let's use 
```
if [ ! -f "$BOOKSTACK_HOME/.env" ]; then
```

File: docker-entrypoint.sh [hunk 2]
```diff
@@ -7,9 +7,9 @@ echoerr() { echo "$@" 1>&2; }
...
   if [[ "${DB_HOST}" ]]; then
-  cat > /var/www/BookStack/.env <<EOF
+  cat > /var/www/bookstack/.env <<EOF
```
Comment (solidnerd) [inline docker-entrypoint.sh]: Here aswell 
```
if [ ! -f "$BOOKSTACK_HOME/.env" ]; then
```

**Comment by hgmich** [comment]
This should be good to go now.

**Comment by solidnerd** [comment]
LGTM !
